default: &default
  adapter: postgresql
  encoding: utf8
  timeout: 5000
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: book_store_develop

test:
  <<: *default
  database: book_store_test


production:
  <<: *default
  database: book_store_production
